### ISSUE TITLE
config.json file does not exist

### ISSUE THREAD

**Issue by harsha0509nm** [iloveitaly/hyper-focus#1]
config.json file does not exist in repository. 
we created our own config file to check schedule but schedule is not applying for it.

![Screenshot 2022-12-28 at 1 02 50 PM](https://user-images.githubusercontent.com/90324753/209775724-ff9a2d62-f032-49b6-847b-e1b0575b087d.png)

![Screenshot 2022-12-28 at 12 58 41 PM](https://user-images.githubusercontent.com/90324753/209775526-0500bce5-0c63-4b0c-9189-efd9e04556d9.png)

**Comment by iloveitaly** [comment]
Thanks for trying this out! Definitely still very beta, so there are probably issues.

Where is your config file located?

Here's a working example https://github.com/iloveitaly/dotfiles/blob/master/.config/focus/config.json

**Comment by iloveitaly** [comment]
Closing this out, feel free to reopen.

**Comment by nikspyratos** [comment]
Installing by brew does not initialise a config file, or at least doesn't in a location that the program expects when being started manually.
