### ISSUE TITLE
Problems with homebrew installation

### ISSUE THREAD

**Issue by BangGang6969** [iloveitaly/hyper-focus#3]
I've tried default homebrew  installation via terminal about 5 times and it displayed same error
```
=> swift build --disable-sandbox -c release
Last 15 lines from /Users/—/Library/Logs/Homebrew/hyper-focus/01.swift:
2023-04-01 13:36:50 +0000

swift
build
--disable-sandbox
-c
release

error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

**Comment by iloveitaly** [comment]
@BangGang6969 could you try running `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer` to see if that fixes the issue?

The real fix is getting precompiled bottles, but I'm not sure that's possible if it's not hosted within the main homebrew repo :/

**Comment by iloveitaly** [comment]
@BangGang6969 curious if the `Xcode-select` fixed the issue?

**Comment by iloveitaly** [comment]
Closing this out, feel free to reopen.
